// <auto-generated />
using System;
using ChurrascariaSystem.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ChurrascariaSystem.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251208212510_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ChurrascariaSystem.Domain.Entities.ItemPedido", b =>
                {
                    b.Property<int>("idItemPedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idItemPedido"));

                    b.Property<string>("Observacao")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("PrecoUnitario")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("idPedido")
                        .HasColumnType("int");

                    b.Property<int>("idProduto")
                        .HasColumnType("int");

                    b.HasKey("idItemPedido");

                    b.HasIndex("idPedido");

                    b.HasIndex("idProduto");

                    b.ToTable("ItensPedido", (string)null);
                });

            modelBuilder.Entity("ChurrascariaSystem.Domain.Entities.Mesa", b =>
                {
                    b.Property<int>("idMesa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idMesa"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<int>("Capacidade")
                        .HasColumnType("int");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("idMesa");

                    b.HasIndex("Numero")
                        .IsUnique();

                    b.ToTable("Mesas", (string)null);

                    b.HasData(
                        new
                        {
                            idMesa = 1,
                            Ativo = true,
                            Capacidade = 4,
                            Numero = "1",
                            Status = 1
                        },
                        new
                        {
                            idMesa = 2,
                            Ativo = true,
                            Capacidade = 4,
                            Numero = "2",
                            Status = 1
                        },
                        new
                        {
                            idMesa = 3,
                            Ativo = true,
                            Capacidade = 6,
                            Numero = "3",
                            Status = 1
                        },
                        new
                        {
                            idMesa = 4,
                            Ativo = true,
                            Capacidade = 2,
                            Numero = "4",
                            Status = 1
                        },
                        new
                        {
                            idMesa = 5,
                            Ativo = true,
                            Capacidade = 4,
                            Numero = "5",
                            Status = 1
                        });
                });

            modelBuilder.Entity("ChurrascariaSystem.Domain.Entities.Pedido", b =>
                {
                    b.Property<int>("idPedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idPedido"));

                    b.Property<DateTime>("DataPedido")
                        .HasColumnType("datetime2");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("StatusPedidoValor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Status");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("idMesa")
                        .HasColumnType("int");

                    b.Property<int>("idUsuario")
                        .HasColumnType("int");

                    b.HasKey("idPedido");

                    b.HasIndex("idMesa");

                    b.HasIndex("idUsuario");

                    b.ToTable("Pedidos", (string)null);
                });

            modelBuilder.Entity("ChurrascariaSystem.Domain.Entities.Produto", b =>
                {
                    b.Property<int>("idProduto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idProduto"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImagemUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("PrecoValor")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("Preco");

                    b.Property<int>("idTipoProduto")
                        .HasColumnType("int");

                    b.HasKey("idProduto");

                    b.HasIndex("idTipoProduto");

                    b.ToTable("Produtos", (string)null);

                    b.HasData(
                        new
                        {
                            idProduto = 1,
                            Ativo = true,
                            Descricao = "Espetinho de picanha suculenta",
                            Nome = "Churrasquinho de Picanha",
                            PrecoValor = 12.00m,
                            idTipoProduto = 1
                        },
                        new
                        {
                            idProduto = 2,
                            Ativo = true,
                            Descricao = "Espetinho de coração de frango",
                            Nome = "Churrasquinho de Coração",
                            PrecoValor = 8.00m,
                            idTipoProduto = 1
                        },
                        new
                        {
                            idProduto = 3,
                            Ativo = true,
                            Descricao = "Espetinho de frango temperado",
                            Nome = "Churrasquinho de Frango",
                            PrecoValor = 7.00m,
                            idTipoProduto = 1
                        },
                        new
                        {
                            idProduto = 4,
                            Ativo = true,
                            Descricao = "Pão, calabresa, queijo e molhos",
                            Nome = "Completo de Calabresa",
                            PrecoValor = 15.00m,
                            idTipoProduto = 2
                        },
                        new
                        {
                            idProduto = 5,
                            Ativo = true,
                            Descricao = "Refrigerante Coca-Cola lata",
                            Nome = "Coca-Cola 350ml",
                            PrecoValor = 5.00m,
                            idTipoProduto = 3
                        },
                        new
                        {
                            idProduto = 6,
                            Ativo = true,
                            Descricao = "Batata frita crocante",
                            Nome = "Porção de Batata Frita",
                            PrecoValor = 18.00m,
                            idTipoProduto = 4
                        });
                });

            modelBuilder.Entity("ChurrascariaSystem.Domain.Entities.TipoProduto", b =>
                {
                    b.Property<int>("idTipoProduto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idTipoProduto"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Descricao")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("idTipoProduto");

                    b.ToTable("TiposProduto", (string)null);

                    b.HasData(
                        new
                        {
                            idTipoProduto = 1,
                            Ativo = true,
                            Descricao = "Espetinhos variados",
                            Nome = "Espetinhos"
                        },
                        new
                        {
                            idTipoProduto = 2,
                            Ativo = true,
                            Descricao = "Lanches completos",
                            Nome = "Completos"
                        },
                        new
                        {
                            idTipoProduto = 3,
                            Ativo = true,
                            Descricao = "Bebidas variadas",
                            Nome = "Bebidas"
                        },
                        new
                        {
                            idTipoProduto = 4,
                            Ativo = true,
                            Descricao = "Porções diversas",
                            Nome = "Porções"
                        });
                });

            modelBuilder.Entity("ChurrascariaSystem.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("idUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idUsuario"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataModificacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("TipoUsuario")
                        .HasColumnType("int");

                    b.HasKey("idUsuario");

                    b.HasIndex("Cpf")
                        .IsUnique();

                    b.ToTable("Usuarios", (string)null);

                    b.HasData(
                        new
                        {
                            idUsuario = 1,
                            Ativo = true,
                            Cpf = "14847384628",
                            DataCriacao = new DateTime(2025, 12, 8, 18, 25, 8, 400, DateTimeKind.Local).AddTicks(3602),
                            DataModificacao = new DateTime(2025, 12, 8, 18, 25, 8, 400, DateTimeKind.Local).AddTicks(3618),
                            Nome = "Administrador",
                            Senha = "$2a$11$AgLmWqXKvJnm6Eudyd.EheXvw20jnCvnZ90Nk8tVC8kYM13g5srYi",
                            TipoUsuario = 1
                        },
                        new
                        {
                            idUsuario = 2,
                            Ativo = true,
                            Cpf = "56757472651",
                            DataCriacao = new DateTime(2025, 12, 8, 18, 25, 8, 566, DateTimeKind.Local).AddTicks(6588),
                            DataModificacao = new DateTime(2025, 12, 8, 18, 25, 8, 566, DateTimeKind.Local).AddTicks(6607),
                            Nome = "Garçom1",
                            Senha = "$2a$11$FKX1fDrPmv1A4gt4yQNkVuVITtJRmLBipRJH0J8Ul2PKFSmPTEJoS",
                            TipoUsuario = 2
                        });
                });

            modelBuilder.Entity("ChurrascariaSystem.Domain.Entities.ItemPedido", b =>
                {
                    b.HasOne("ChurrascariaSystem.Domain.Entities.Pedido", "Pedido")
                        .WithMany("Itens")
                        .HasForeignKey("idPedido")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChurrascariaSystem.Domain.Entities.Produto", "Produto")
                        .WithMany("ItensPedido")
                        .HasForeignKey("idProduto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pedido");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("ChurrascariaSystem.Domain.Entities.Pedido", b =>
                {
                    b.HasOne("ChurrascariaSystem.Domain.Entities.Mesa", "Mesa")
                        .WithMany("Pedidos")
                        .HasForeignKey("idMesa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ChurrascariaSystem.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("idUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Mesa");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ChurrascariaSystem.Domain.Entities.Produto", b =>
                {
                    b.HasOne("ChurrascariaSystem.Domain.Entities.TipoProduto", "TipoProduto")
                        .WithMany("Produtos")
                        .HasForeignKey("idTipoProduto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TipoProduto");
                });

            modelBuilder.Entity("ChurrascariaSystem.Domain.Entities.Mesa", b =>
                {
                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("ChurrascariaSystem.Domain.Entities.Pedido", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("ChurrascariaSystem.Domain.Entities.Produto", b =>
                {
                    b.Navigation("ItensPedido");
                });

            modelBuilder.Entity("ChurrascariaSystem.Domain.Entities.TipoProduto", b =>
                {
                    b.Navigation("Produtos");
                });
#pragma warning restore 612, 618
        }
    }
}
